[pytest]

testpaths = tests

python_files = test_*.py

addopts = -v -s --html=reports/report.html

pythonpath = .

markers =
    ui: Web UI tests
    api: API tests
    unit: Unit and parameterized tests